theme: minima
title: AP Comp Sci Website
author: Jonathan Roy Varghese
email: jroyvarghese@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is a website that I made using the version control system of GitHub. This website follows two of the free courses offered
  on GitHub - the Introductory Course and the GitHub Pages course. This was fun to make. 
  
  Snapchat Username : thetyrantgamer
  Steam Username : Phantom
 

# social links
twitter_username: thetyrantgamer 
github_username:  J-R-V-EB # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
